import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import java.awt.ActionEvent;
import java.awt.ActionListener;
import javax.swing.JButton;
import java.util.Arrays;

public class Location extends JButton implements ActionListener{
    private boolean[] walls;
    private Player p;
    public Location (JSONObject o){
        JSONArray wallList = (JSONArray) o.get("walls");
        this.walls = new boolean[wallList.size()];
        for (int i = 0; i < walls.length; i++){
            this.walls[i] = (boolean) wallList.get(i);

        }

    }
    @Override
    public void actionPerformed(ActionEvent e){
        // AUTOGENERATEDMETHODSTUB
    }
    @Override
    public String toString(){
        return Arrays.toString(walls);
    }

}
